

services:
  backend:
    build: .
    container_name: vocalii_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    volumes:
      - ./uploads:/app/uploads

  db:
    image: postgres:16
    container_name: vocalii_db
    environment:
      POSTGRES_DB: vocali_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ukraine2018!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: